name: account-lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/checkout@v1

      - run: npm install
      - run: npm run lint
        env:
          CI: true

      - run: npm run tslint
        env:
          CI: true
